version: "3.9"

services:
  hardhat:
    container_name: hardhat
    hostname: hardhat
    network_mode: bridge
    image: hardhat-network:latest
    restart: always
    ports:
      - 8545:8545
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
